### ISSUE TITLE
Dictionary needs a callback

### ISSUE THREAD

**Issue by viperfx** [Localize/node-localizejs#2]
I have noticed that the contents of the dictionary is performing an async operation and therefore when the `toObject` is called in a script the contents are empty. The work around right now is to use something like setTimeout of 500.

```
var localizejs = require('localizejs');

var client = localizejs.createClient({
    publicKey: 'public-key',
    privateKey: 'private-key'
});

var project = client.project('project-key');

var dictionary = project.dictionary('fr');

console.log(dictionary.toObject()); // this returns {}, in a set timeout it will return the correct object.
```

It would be good to have a callback arg on `dictionary` to ensure the object has been populated properly.

**Comment by paton** [comment]
Good catch, there should be a callback here.

Here's a workaround you can use until we add this:

    var dictionary = project.dictionary('fr');

    dictionary._onready(function() {
      console.log(dictionary.toObject());
    });
